CREATE OR REPLACE PACKAGE CUSTOMER_MANAGER AS
FUNCTION GET_TOTAL_PURCHASE(p_customer_id NUMBER) RETURN NUMBER;
PROCEDURE ASSIGN_GIFTS_TO_ALL;
END CUSTOMER_MANAGER;
/

CREATE OR REPLACE PACKAGE BODY CUSTOMER_MANAGER IS
FUNCTION CHOOSE_GIFT_PACKAGE(p_total_purchase NUMBER) RETURN NUMBER IS
v_result NUMBER;
BEGIN
    CASE
    WHEN p_total_purchase >= 10000 THEN v_result := 3;
    WHEN p_total_purchase < 10000 AND p_total_purchase >= 1000 THEN v_result := 2;
    WHEN p_total_purchase >= 100 THEN v_result := 1;
    ELSE v_result := NULL;
    END CASE;

    RETURN v_result;
END CHOOSE_GIFT_PACKAGE;

FUNCTION GET_TOTAL_PURCHASE(p_customer_id NUMBER) RETURN NUMBER AS
v_total_purchase NUMBER;
BEGIN
    SELECT SUM(UNIT_PRICE * QUANTITY) INTO v_total_purchase FROM ORDER_ITEMS 
    JOIN ORDERS USING(ORDER_ID)
    WHERE CUSTOMER_ID = p_customer_id;

    RETURN v_total_purchase;
END GET_TOTAL_PURCHASE;

PROCEDURE ASSIGN_GIFTS_TO_ALL AS
v_gift_package_result NUMBER;
BEGIN
    FOR r IN(SELECT UNIQUE CUSTOMER_ID, EMAIL_ADDRESS 
             FROM CUSTOMERS
             WHERE EMAIL_ADDRESS NOT IN (SELECT CUSTOMER_EMAIL FROM CUSTOMER_REWARDS)) 
                LOOP
                    v_gift_package_result := CHOOSE_GIFT_PACKAGE(GET_TOTAL_PURCHASE(r.CUSTOMER_ID));
                    INSERT INTO CUSTOMER_REWARDS(CUSTOMER_EMAIL, GIFT_ID) VALUES(r.EMAIL_ADDRESS, v_gift_package_result);
                END LOOP;
END ASSIGN_GIFTS_TO_ALL;

END CUSTOMER_MANAGER;
/